apiVersion: kelemetry.kubewharf.io/v1alpha1
kind: LinkRule
metadata:
  name: pod-secret
sourceFilter:
  resources:
    - group: ""
      resource: pods
targetTemplate:
  group: ""
  version: v1
  resource: secrets
  namespaceTemplate: "{{.metadata.namespace}}"
  nameTemplate: |
    {{- range .spec.volumes -}}
      {{- if .secret -}}
        {{- .secret.secretName -}},
      {{- end -}}
    {{- end -}}
link:
  targetRole: Child
  class: volumes
