---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-frontend
  labels: {{ include "kelemetry.frontend-labels" . }}
spec:
  replicas: {{.Values.frontend.replicaCount}}
  selector:
    matchLabels: {{ include "kelemetry.frontend-labels" . }}
  template:
    metadata:
      labels: {{ include "kelemetry.frontend-labels" . }}
    spec:
      imagePullSecrets: [
        {{- range .Values.kelemetryImage.pullSecrets }}
        {{ . | toJson }},
        {{- end }}
        {{- range .Values.jaegerImages.pullSecrets }}
        {{ . | toJson }},
        {{- end }}
      ]
      {{ include "kelemetry.pod-boilerplate" .Values.frontend | nindent 6 }}
      containers:
        - name: jaeger-query
          {{ include "kelemetry.container-boilerplate" .Values.frontend.jaegerQuery | nindent 10 }}
          image: {{ printf "%s:%s" .Values.jaegerImages.query.repository .Values.jaegerImages.query.tag | toJson }}
          imagePullPolicy: {{ toJson .Values.jaegerImages.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /
              port: admin
          readinessProbe:
            httpGet:
              path: /
              port: admin
          ports:
            - name: query
              containerPort: 16686
            - name: grpc
              containerPort: 16685
            - name: admin
              containerPort: 16687
          env:
            - name: GRPC_STORAGE_SERVER
              value: localhost:17271
            - name: SPAN_STORAGE_TYPE
              value: grpc-plugin
        - name: storage-plugin
          {{ include "kelemetry.container-boilerplate" .Values.frontend.storagePlugin | nindent 10 }}
          image: {{ printf "%s:%s" .Values.kelemetryImage.repository (.Values.kelemetryImage.tag | default .Chart.AppVersion) | toJson }}
          imagePullPolicy: {{ toJson .Values.kelemetryImage.pullPolicy }}
          # TODO: add readiness probe
          command: [
            "/usr/local/bin/kelemetry",
            {{ include "kelemetry.logging-options" .Values.frontend.storagePlugin }}
            {{ include "kelemetry.storage-plugin-options" . }}
          ]
          ports: [
            {
              name: storage-grpc,
              containerPort: 17271,
            },
            {
              name: extension,
              containerPort: 8080,
            },
            {{- include "kelemetry.observe-ports" .Values.frontend.storagePlugin }}
          ]

---
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-query
  labels: {{ include "kelemetry.frontend-labels" . }}
{{- with .Values.frontend.service }}
spec:
  type: {{toJson .type}}
  {{- if .otherConfig }}
  {{- toYaml .otherConfig | nindent 2 }}
  {{- end }}
  selector: {{ include "kelemetry.frontend-labels" $ }}
  ports:
    - name: query
      port: 16686
      targetPort: query
      {{- if .queryNodePort }}
      nodePort: {{toJson .queryNodePort}}
      {{- end }}
    - name: extension
      port: 8080
      targetPort: extension
      {{- if .redirectNodePort }}
      nodePort: {{toJson .redirectNodePort}}
      {{- end }}
{{- end }}
