name: CI

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test:
    name: Run unit tests
    runs-on: [ubuntu-20.04]
    permissions:
      checks: write
      statuses: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: Run unit tests
        run: make test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  lint:
    name: golangci-lint
    runs-on: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: Run lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout=10m
          only-new-issues: true

  typos:
    name: Check typos
    runs-on: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v3
      - uses: crate-ci/typos@master
        with:
          config: hack/typos.toml
